baseURL = 'https://jingwangtw.github.io/dark-theme-editor/'
languageCode = 'en-us'
title = 'Example Site of dark-theme-editor'
theme = 'dark-theme-editor'

# Theme parameter
[Params]
    # CopyRight string in the footer, change it to "" hide it
    copyrightStr = 'All Rights Reserved.'
    
    # This name would be shown in the bottom of the page. It indicates the author of the site.
    authorName = 'Jing'

    # Should include Table of Content in front of the page or not.
    includeToc = true
    
    # Social link in the footer, change it to "" hide it
    [Social]
        github = "https://github.com/JingWangTW"
        email = "tony.jing.wang@gmail.com"